title: Arc
email: vin@misday.com
description: ""
baseurl: ""
url: ""

# Build settings

remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme

show_downloads: false
google_analytics: UA-28333273-1
